// <auto-generated />
using System;
using MenuManager.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuManager.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403190623_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuManager.Shared.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.DayPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MenuPlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuPlanId");

                    b.ToTable("DayPlans");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.ItemSupplier", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("SupplierReference")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ItemId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ItemSuppliers");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.MealSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DayPlanId", "MealType")
                        .IsUnique();

                    b.ToTable("MealSlots");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.MealSlotItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("MealSlotId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MealSlotId");

                    b.ToTable("MealSlotItems");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.MenuPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("MenuPlans");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Party");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Customer", b =>
                {
                    b.HasBaseType("MenuManager.Shared.Entities.Party");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Supplier", b =>
                {
                    b.HasBaseType("MenuManager.Shared.Entities.Party");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("Siret")
                        .HasColumnType("text");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Category", b =>
                {
                    b.HasOne("MenuManager.Shared.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.DayPlan", b =>
                {
                    b.HasOne("MenuManager.Shared.Entities.MenuPlan", "MenuPlan")
                        .WithMany("DayPlans")
                        .HasForeignKey("MenuPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuPlan");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Item", b =>
                {
                    b.HasOne("MenuManager.Shared.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.ItemSupplier", b =>
                {
                    b.HasOne("MenuManager.Shared.Entities.Item", "Item")
                        .WithMany("ItemSuppliers")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuManager.Shared.Entities.Supplier", "Supplier")
                        .WithMany("ItemSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.MealSlot", b =>
                {
                    b.HasOne("MenuManager.Shared.Entities.DayPlan", "DayPlan")
                        .WithMany("MealSlots")
                        .HasForeignKey("DayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayPlan");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.MealSlotItem", b =>
                {
                    b.HasOne("MenuManager.Shared.Entities.Item", "Item")
                        .WithMany("MealSlotItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuManager.Shared.Entities.MealSlot", "MealSlot")
                        .WithMany("MealSlotItems")
                        .HasForeignKey("MealSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("MealSlot");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.MenuPlan", b =>
                {
                    b.HasOne("MenuManager.Shared.Entities.Customer", "Customer")
                        .WithMany("MenuPlans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Customer", b =>
                {
                    b.HasOne("MenuManager.Shared.Entities.Party", null)
                        .WithOne()
                        .HasForeignKey("MenuManager.Shared.Entities.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Supplier", b =>
                {
                    b.HasOne("MenuManager.Shared.Entities.Party", null)
                        .WithOne()
                        .HasForeignKey("MenuManager.Shared.Entities.Supplier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Category", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.DayPlan", b =>
                {
                    b.Navigation("MealSlots");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Item", b =>
                {
                    b.Navigation("ItemSuppliers");

                    b.Navigation("MealSlotItems");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.MealSlot", b =>
                {
                    b.Navigation("MealSlotItems");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.MenuPlan", b =>
                {
                    b.Navigation("DayPlans");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Customer", b =>
                {
                    b.Navigation("MenuPlans");
                });

            modelBuilder.Entity("MenuManager.Shared.Entities.Supplier", b =>
                {
                    b.Navigation("ItemSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
